### ISSUE TITLE
Access Forbidden on Windows / Xampp

### ISSUE THREAD

**Issue by contactwajeeh** [enajeeb/phalcon-boilerplate#4]
I am able to set up the app, but I am getting only signin page, all the rest of the links are throwing the 403 error. can you please help me, as to what I am doing wrong. I am new to Phalcon and very impressed by its features.

my vhosts
<<VirtualHost *:80>
    ServerName server
    ServerAdmin <your-email-address>
    DocumentRoot "C:\xampp\htdocs\phalcon-app\public"
    DirectoryIndex "index.html" "index.php"
    <Directory "C:\xampp\htdocs\phalcon-app\public">
        Options +Indexes +FollowSymLinks +MultiViews +Includes
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>>

and my config is set to this:

'baseUrl'                  => 'http://server',

Please help me out.

**Comment by contactwajeeh** [comment]
This is fixed, by editing the htaccess files. Please close the issue.

**Comment by enajeeb** [comment]
Thanks. Let me know if you come across any other issues.

**Comment by ghost** [comment]
same issue here, could you tell me how did you solved it?, thank´s in advance.
(403 Access Forbidden , using xampp on windows)

**Comment by enajeeb** [comment]
Can you share your vhost and .htaccess files?

**Comment by ghost** [comment]
httpd-vhosts.conf:
![captura de pantalla 289](https://cloud.githubusercontent.com/assets/13488038/12106989/b1c520a8-b32a-11e5-81f2-08a0d0bc7878.png)

.htaccess:
![captura de pantalla 290](https://cloud.githubusercontent.com/assets/13488038/12107016/fe6c1362-b32a-11e5-93b8-dda3f0088c1e.png)

**Comment by enajeeb** [comment]
Make sure permission for your document root and public folder is at least 755

**Comment by drewswaycool** [comment]
Running on Windows 10 with Xampp 3.2.2. I cannot resolve this issue.

This is my httpd-vhosts.conf

```
<VirtualHost phalcon.local:80>
    ServerAdmin webmaster@phalcon.local
    DocumentRoot "C:/xampp/htdocs/phalcon"
    ServerName phalcon.local
    ServerAlias www.phalcon.local
    ErrorLog "logs/phalcon.local-error.log"
    CustomLog "logs/phalcon.local-access.log" common
    <Directory "C:/xampp/htdocs/phalcon/">
        Require all granted    
    </Directory>
</VirtualHost>
```

Apache/2.4.17
