### ISSUE TITLE
Missing vendor directory

### ISSUE THREAD

**Issue by drewswaycool** [enajeeb/phalcon-boilerplate#5]
`bootstrap.php`

is attempting to require a file that is not present in the repo (there is no vendor directory)

> Warning: require_once(C:\xampp\htdocs\phalcon/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\phalcon\app\config\bootstrap.php on line 199
> 
> Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\phalcon/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\phalcon\app\config\bootstrap.php on line 199

**Comment by enajeeb** [comment]
You have to run "php composer.phar install" in the project directory which will create vendor directory.

**Comment by drewswaycool** [comment]
Thanks I assumed I was missing a step like this.
